sef-global/academix-frontend

README.md
- The purpose of this PR is to fix #5 
- Update missing instruction in readme
- Update missing instruction in `README.md`
=> Update missing instruction in readme

app/src/index.tsx, app/src/scenes/Home/components/catogories/index.tsx, app/src/scenes/Home/components/catogories/interfaces.ts, app/src/scenes/Home/components/catogories/styles.css, app/src/scenes/Home/index.tsx
- The purpose of this PR is to fix #7 
- List categories for Academix
- Add `components` directory under the `Home` directory 
- Create a `category` component 
- Render the categories
=> List categories for Academix

app/src/scenes/Home/components/catogories/index.tsx, app/src/scenes/Home/components/catogories/interfaces.ts, app/src/scenes/Home/index.tsx
- The purpose of this PR is to fix #9 
- Update the interface according to the new payload structure
- Changed the `interfaces.ts` file for the category component
- Changed the `index.tsx` according to the interface.
#8
=> Update the interface according to the new payload structure

app/src/scenes/Items/index.tsx, app/src/scenes/Items/interfaces.ts, app/src/scenes/Items/styles.module.css
The purpose of this PR is to fix #13 
To create a model to display the item description and link when clicked
Implemented using ant design model component
N/A
- Google chrome
- Tomcat 9
- Java OpenJDK 11
- macOS Catalina 10.15.3
- https://ant.design/components/modal/
=> Add model to be displayed on click of an item

app/src/scenes/Home/components/catogories/index.tsx
The purpose of this PR is to fix #15 
To fix the bug in categories index file
Add missing 'else' statement to catch error.
=> Handle non 200 statuses in category view

app/src/scenes/SubCategories/index.tsx
- The purpose of this PR is to fix #19 
- Fix the bug
- Change the translation array index to 0.
=> Fix category name not loading error

app/src/scenes/Home/components/catogories/index.tsx, app/src/scenes/SubCategories/index.tsx
- The purpose of this PR is to fix #21 
- Fix the issue
- Fix the issue of breaking URLs
=> Fix the issue of breaking urls

scripts/deploy.sh
To fix https://github.com/sef-global/academix-frontend/issues/26
Make Travis deploy success
Remove the unnecessary line from the deploy script
https://github.com/sef-global/academix-frontend/pull/24
Build environment: Apache Maven 3.6.3
Deploy environment: Ubuntu 18.04.3 LTS, MySQL Ver 8.0.18
N/A
=> Remove unnecessary code line

app/src/index.tsx, app/src/scenes/Items/index.tsx, app/src/scenes/Items/interfaces.ts, app/src/scenes/Items/styles.module.css, app/src/scenes/SubCategories/index.tsx, app/src/scenes/SubCategories/interfaces.ts, app/src/scenes/SubCategories/styles.module.css
- The purpose of this PR is to fix #29 
- Reduce steps to get to the items
- Render the `items` component in the subcategory scene
=> Create the items view in the subcategory scene

app/src/components/App/index.tsx, app/src/components/App/styles.css, app/src/scenes/Home/index.tsx
The purpose of this PR is to fix #31 
To add a new footer & edit the header
1. Added a new footer
2. Edited the header
3. Fixed the alignments
=> Add footer & edit header

app/src/index.html
The purpose of this PR is to fix #36 
To add UTF-8 meta tag to academix.
Add the required tag in index.html file
=> Add UTF-8 metatag to the index.html page

app/src/index.html
The purpose of this PR is to fix #36 
Remove the invalid character from the footer
Add the required tag in index.html file
=> Add correct UTF-8 metatag in index.html

app/src/components/App/index.tsx
- The purpose of this PR is to fix #42 
- Link the SEF logo to the SEF site
- Use `<a>` instead of `<Link>` component
=> Link sef-logo in header to SEF homepage

app/src/components/App/styles.css, app/src/scenes/SubCategories/index.tsx
- The purpose of this PR is to fix #44 
- Hide the comment from the page.
- Replace the todo comment with the correct syntax
- Add a margin for the footer
=> Replace the todo comment with the correct syntax

app/src/components/App/index.tsx, app/src/components/App/styles.css
- The purpose of this PR is to fix #46 
- Make the header and the footer responsive in mobile view
- Add SEF logo as a menu item
- Remove menu item from the footer
=> Make the header and the footer responsive

app/src/scenes/Home/index.tsx, app/src/scenes/Home/styles.module.css
The purpose of this PR is to fix #52 
To add the SEF email so that users can give feedback regarding Academix project.
1. Added the SEF email with a brief description.
2. Linked "info@sefglobal.org" directly to compose a new email.
=> Add sef-email to contact regarding new content

app/src/interfaces.ts, app/src/scenes/SubCategories/index.tsx
The purpose of this PR is to fix #58 
Improving the readability of academix URLs
Added the subcategory name to the URLs
N/A
Ubuntu 19.04
OpenJDK 1.8
Tomcat 7
N/A
=> Add subcategory names to URLs

app/src/interfaces.ts, app/src/scenes/Home/components/catogories/index.tsx, app/src/scenes/SubCategories/index.tsx, app/src/scenes/SubCategories/scenes/Items/index.tsx, app/src/scenes/SubCategories/scenes/Items/interfaces.ts
The purpose of this PR is to fix #61 
To fix the frontend according to the new payload.
1. Remove (category, sub-category, item) translation arrays from interfaces
2. Adjust (category, sub-category, item) interfaces accordingly
3. Refracted the above changes in the entire directory
=> Fix the data according to new payload

app/package.json, app/src/components/App/index.tsx, app/src/scenes/Home/components/catogories/index.tsx, app/src/scenes/SubCategories/scenes/Items/index.tsx, app/src/services/util/googleAnalytics.js
The purpose of this PR is to fix #55 
Implement a way to track user's activities
Initialize Google analytics
Created a util for track views
N/A
https://medium.com/google-cloud/tracking-site-visits-on-react-app-hosted-in-google-cloud-using-google-analytics-f49c2411d398
=> Initialize google analytics on Academix

app/src/components/App/index.tsx
The purpose of this PR is to fix #66
To replace the new blog URL 
Replaced the old URL with https://sefglobal.medium.com/
=> Correct the blog url in navbar

app/package.json, app/src/components/App/index.tsx
The purpose of this PR is to fix #65
To update the year in the footer
Updated the year in the footer
=> Update the year in footer
